name: Deploy
description: Deploy a Rhino app to branch
inputs:
  branches:
    description: Which branches to create deployments for?
    default: main master
  force:
    description: Deploy even if branch doesn't match?
    default: false
runs:
  using: composite
  steps:
    - name: Parse inputs
      id: parse
      env:
        BRANCHES: ${{ inputs.branches }}
      shell: python
      run: |
        import json, os
        branches = json.dumps(os.environ['BRANCHES'].split())
        with open(os.environ['GITHUB_ENV'], 'w') as env:
          env.write(f'BRANCHES={branches}\n')

    - name: Write manifest
      shell: Rscript {0}
      run: |
        renv::install("rsconnect")
        rsconnect::writeManifest()

    - name: Prepare deployment
      shell: bash
      run: |
        files=(
          .Rprofile
          app
          app.R
          config.yml
          manifest.json
          rhino.yml
        )
        mkdir build
        mv "${files[@]}" build

    - name: Deploy to branch
      # This action was designed for GitHub Pages deployments, but it works perfectly here.
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        dry-run: ${{ !fromJSON(inputs.force) && !contains(fromJSON(env.BRANCHES), github.ref_name) }}
        branch: bot/deploy/${{ github.ref_name }}
        folder: build
